apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: roboshop-microservices
  namespace: argocd
spec:
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: app-group
              operator: In
              values: ["db"]
          maxUpdate: 1
        - matchExpressions:
            - key: app-group
              operator: In
              values: ["app"]
          maxUpdate: 1
  
  generators:
  - list:
      elements:
        - name: mongodb
          valuesPath: envs/dev/mongodb
          group: db
        - name: redis
          valuesPath: envs/dev/redis
          group: db
        - name: mysql
          valuesPath: envs/dev/mysql
          group: db
        - name: rabbitmq
          valuesPath: envs/dev/rabbitmq
          group: db
        - name: catalogue
          valuesPath: envs/dev/catalogue
          group: app
        - name: user
          valuesPath: envs/dev/user
          group: app
        - name: cart
          valuesPath: envs/dev/cart
          group: app
        - name: shipping
          valuesPath: envs/dev/shipping
          group: app
        - name: payment
          valuesPath: envs/dev/payment
          group: app
        - name: frontend
          valuesPath: envs/dev/frontend
          group: app

  template:
    metadata:
      name: '{{name}}'
      labels:
        app-group: '{{group}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/sivaram-ops/cd-roboshop.git
        targetRevision: HEAD
        path: roboshop-microservice
        helm:
          valueFiles:
          - '../{{valuesPath}}/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true