worker_processes auto;
pid /tmp/nginx.pid;

events {
  worker_connections 512;
  multi_accept on;
}

http {
  ##
  # Basic Settings
  ##
  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  large_client_header_buffers 6 32k;
  client_max_body_size 10m;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  ##
  # Logging Settings
  ##
  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log warn; #debug for troubleshoot and warn for production.

  ##
  # Gzip Settings
  ##
  gzip on;
  gzip_disable "msie6";
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  ##
  # Virtual Host Configs
  ##
  server {
    listen       8080; # port 8080 for non-root execution
    server_name  _;    # Catch-all

    proxy_http_version 1.1;

    # Temp paths for non-root execution
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        ssi    on;
    }

    location /images/ {
        expires 5s;
        root   /usr/share/nginx/html;
        try_files $uri /images/placeholder.png;
    }

    # error_page  404              /404.html;
    # redirecting server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # Microservice Proxies
    location /api/catalogue/ { 
      proxy_pass http://catalogue:8080/; 
    }
    location /api/user/ { 
      proxy_pass http://user:8080/; 
    }
    location /api/cart/ { 
      proxy_pass http://cart:8080/; 
    }
    location /api/shipping/ { 
      proxy_pass http://shipping:8080/; 
    }
    location /api/payment/ { 
      proxy_pass http://payment:8080/; 
    }
  }
}
