networks:
  default:
    name: roboshop
    external: true

volumes:
  mongodb:
    name: roboshop-mongodb
    external: true
  redis:
    name: roboshop-redis
    external: true
  mysql:
    name: roboshop-mysql
    external: true
  rabbitmq:
    name: roboshop-rabbitmq
    external: true

services:
  mongodb:
    build:
      context: ./source-code/mongodb
      dockerfile: ./../../dockerfiles/mongodb.Dockerfile
    image: sivaram0101/mongodb-roboshop:v11
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume

  redis:
    build:
      context: ./source-code/redis
      dockerfile: ./../../dockerfiles/redis.Dockerfile
    image: sivaram0101/redis-roboshop:v11
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  mysql:
    build:
      context: ./source-code/mysql
      dockerfile: ./../../dockerfiles/mysql.Dockerfile
    image: sivaram0101/mysql-roboshop:v11
    container_name: mysql
    environment:
      MYSQL_DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume

  rabbitmq:
    build:
      context: ./source-code/rabbitmq
      dockerfile: ./../../dockerfiles/rabbitmq.Dockerfile
    image: sivaram0101/rabbitmq-roboshop:v11
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
    - "15672:15672"
    - "5672:5672"
    volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume

  catalogue:
    build:
      context: ./source-code/catalogue
      dockerfile: ./../../dockerfiles/catalogue.Dockerfile
    image: sivaram0101/catalogue-roboshop:v11
    container_name: catalogue
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
      CATALOGUE_SERVER_PORT: 8080
      MONGO: true
    depends_on:
    - mongodb

  user:
    build:
      context: ./source-code/user
      dockerfile: ./../../dockerfiles/user.Dockerfile
    image: sivaram0101/user-roboshop:v11
    container_name: user
    environment:
      REDIS_HOST: ${REDIS_HOST}
      MONGO_URL: "mongodb://mongodb:27017/users"
      MONGO: true
    depends_on:
    - mongodb
    - redis

  cart:
    build:
      context: ./source-code/cart
      dockerfile: ./../../dockerfiles/cart.Dockerfile
    image: sivaram0101/cart-roboshop:v11
    container_name: cart
    environment:
      REDIS_HOST: ${REDIS_HOST}
      CATALOGUE_HOST: ${CATALOGUE_HOST}
      CATALOGUE_PORT: ${CATALOGUE_PORT}
    depends_on:
    - catalogue
    - redis

  shipping:
    build:
      context: ./source-code/shipping
      dockerfile: ./../../dockerfiles/shipping.Dockerfile
    image: sivaram0101/shipping-roboshop:v11
    container_name: shipping
    environment:
      CART_HOST: ${CART_HOST}
      CART_PORT: ${CART_PORT}
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      CART_ENDPOINT: ${CART_ENDPOINT}
    depends_on:
    - mysql

  payment:
    build:
      context: ./source-code/payment
      dockerfile: ./../../dockerfiles/payment.Dockerfile
    image: sivaram0101/payment-roboshop:v11
    container_name: payment
    environment:
      CART_HOST: ${CART_HOST}
      CART_PORT: ${CART_PORT}
      USER_HOST: ${USER_HOST}
      USER_PORT: ${USER_PORT}
      AMQP_HOST: ${AMQP_HOST}
      AMQP_USER: ${AMQP_USER}
      AMQP_PASS: ${AMQP_PASS}
    depends_on:
    - rabbitmq
    - user
    - cart

  frontend:
    build:
      context: ./source-code/frontend
      dockerfile: ./../../dockerfiles/frontend.Dockerfile
    image: sivaram0101/frontend-roboshop:v11
    container_name: frontend
    ports:
    - "80:8080"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment