- name: Installing Prerequisites
  dnf:
    name:
    - python3
    - gcc
    - python3-devel
    - python3-pip
    state: present

- name: Copying Application Source Code
  copy:
    src: "{{ playbook_dir }}/source-code/{{ microservice }}/app-code/"
    dest: "/home/roboshop/{{ microservice }}/"
    owner: roboshop
    group: roboshop
    mode: '0644'
    directory_mode: '0755'
  notify: Restart Payment App

- name: Installing Dependencies
  pip:
    requirements: "/home/roboshop/payment/requirements.txt"
    executable: pip3
  notify: Restart Payment App

- name: Copying Systemd Service File.
  copy:
    src: "{{ playbook_dir }}/source-code/{{ microservice }}/systemd.service"
    dest: "/etc/systemd/system/{{ microservice }}.service"
    mode: '0644'
  notify: Restart Payment App

- name: Enabling and starting {{  microservice }} application.
  systemd:
    name: "{{ microservice }}"
    enabled: true
    state: started
    daemon_reload: true